/*
	AI_Commander_Decapitate.sqf - AICOM v2 M5 DECAPITATE CLOSER. Server-side, per side.
	Param: _this = side. Runs AFTER the M0 snapshot + the M1 Allocator each strategy tick
	(it NEVER writes wfbe_aicom_targets - the Allocator's town-first fist stays authoritative), gated
	by WFBE_C_AICOM2_DECAP_ENABLE (0 = shadow -> sensing runs + telemetry + side-logic sense-state vars ONLY; no ORDER/stamp writes,
	byte-identical behaviour to HEAD; instant rollback).

	THE MISSING KILL-MOVE. Live evidence 2026-07-04 (ZG, players): the dominant side (EAST, 7 towns
	vs 2, strike posture, armour) ran 116 orders -> 50 arrivals -> 1 begin_capture over 90 min and
	produced ZERO base overruns - froze 2-7-2 because the strike verb RALLIES-AND-HOLDS near the HQ
	instead of pressing onto it. The Allocator concentrates the fist on the nearest capturable TOWN;
	nothing ever commits the army to the enemy HQ itself. This closer is that commit.

	ORGANIC BASE SENSING (owner Q1, 2026-07-06): the commander must not ACT on global HQ knowledge.
	ARM requires all three, sustained across WFBE_C_AICOM2_DECAP_ARM_TICKS net ticks (the streak
	decays by 1 on failing ticks rather than resetting - brief sensor blips do not zero progress): (a) PROXIMITY - at
	least one eligible offensive team leader within DECAP_SENSE_RADIUS (per-map) of the enemy HQ;
	(b) a periodic DICE ROLL - every DECAP_SENSE_INTERVAL strategy ticks, chance DECAP_SENSE_CHANCE,
	latched as 'sensed' until contact is lost; (c) DOMINANCE - myEff >= enEff*DOM_RATIO (a weak side
	that stumbles onto the HQ does not commit). MAX_ENTOWNS is demoted to a secondary safety. Then ->
	COMMITTED. Once COMMITTED it STOPS re-evaluating entry; the only exits are enemy-HQ-dead (win) or
	a deliberately-hard ABORT (myEff < enEff*ABORT_RATIO sustained, and only after MIN_COMMIT seconds).
	Wide hysteresis a momentary garrison dip cannot cross - the leader own garrisoning briefly lowers
	_myStr and the legacy strike auto-recalled on exactly that; this does not.

	COMMIT ACTION (scoped): stamp wfbe_aicom_decap = enHQpos + wfbe_aicom_alloc_target = the enemy town
	nearest the HQ ONLY on teams whose leader is within DECAP_COMMIT_RADIUS of the HQ - nearby teams
	press while the REST OF THE ARMY KEEPS CAPTURING TOWNS (wfbe_aicom_targets is never overwritten;
	distant teams keep their town orders untouched). The driver-press hook consuming the stamp is the
	NEXT increment. Feeds the existing overrun razer -> server_victory_threeway.sqf win = real overrun.

	State on the side logic: wfbe_aicom2_decap_streak, wfbe_aicom2_decap_sensetick (roll cadence),
	wfbe_aicom2_decap_sensed (latch), wfbe_aicom2_decap_committed, wfbe_aicom2_decap_t0. Telemetry AICOM2|v1|DECAP.
	A2-OA-safe: snapshot for tick-stable facts; plain-get + isNil heals (no GROUP 2-arg getVariable, no
	NSSETVAR3, no A3 commands); >0 numeric-flag guards; if/else booleans (no ==/!= on Bool).
*/

private ["_side","_logik","_snap","_myEff","_enEff","_enTowns","_myTowns","_enHQ","_enHQPos","_enHQAlive",
	"_domRatio","_abortRatio","_maxEnTowns","_armTicks","_minCommit","_dominant","_streak","_committed",
	"_t0","_state","_tgtTowns","_teams","_nearTown","_bestD","_d","_t","_stamped","_sideText","_elMin",
	"_senseRadius","_senseInterval","_senseChance","_commitRadius","_senseTick","_sensed","_inRange","_rollNow","_ldr","_garTeam","_holdT","_isHolding","_capLk","_capLocked","_dHQ","_decV","_stallStreak"];

_side = _this;
_logik = (_side) Call WFBE_CO_FNC_GetSideLogic;
if (isNil "_logik") exitWith {};
_snap = _logik getVariable ["wfbe_aicom2_snap", []];
if (count _snap < 26) exitWith {};

_myEff     = _snap select WFBE_SNAP_MYEFF;
_enEff     = _snap select WFBE_SNAP_ENEFF;
_enTowns   = _snap select WFBE_SNAP_ENTOWNS;
_myTowns   = _snap select WFBE_SNAP_MYTOWNS;
_enHQ      = _snap select WFBE_SNAP_ENHQ;
_enHQPos   = _snap select WFBE_SNAP_ENHQPOS;
_enHQAlive = _snap select WFBE_SNAP_ENHQALIVE;
//--- GRUDGE LEDGER (feat/aicom-grudge-ledger, generated by apply_grudge.py): nearest capturable town to the enemy HQ - reused by the ABORT stamp and the optional ARM shortcut
private ["_grNearTown","_grBestD","_grT"];
_grNearTown = objNull;
if ((missionNamespace getVariable ["WFBE_C_AICOM_GRUDGE", 0]) > 0 && {_enHQAlive}) then {
	_grBestD = 1e12;
	{ _grT = (getPos _x) distance _enHQPos; if (_grT < _grBestD) then {_grBestD = _grT; _grNearTown = _x} } forEach (_snap select WFBE_SNAP_TGTTOWNOBJS);
};

_domRatio   = missionNamespace getVariable [format ["WFBE_C_AICOM2_DECAP_DOM_RATIO_%1", _side], missionNamespace getVariable ["WFBE_C_AICOM2_DECAP_DOM_RATIO", 1.5]];
_abortRatio = missionNamespace getVariable [format ["WFBE_C_AICOM2_DECAP_ABORT_RATIO_%1", _side], missionNamespace getVariable ["WFBE_C_AICOM2_DECAP_ABORT_RATIO", 0.9]];
_maxEnTowns = missionNamespace getVariable [format ["WFBE_C_AICOM2_DECAP_MAX_ENTOWNS_%1", _side], missionNamespace getVariable ["WFBE_C_AICOM2_DECAP_MAX_ENTOWNS", 5]];
_armTicks   = missionNamespace getVariable [format ["WFBE_C_AICOM2_DECAP_ARM_TICKS_%1", _side], missionNamespace getVariable ["WFBE_C_AICOM2_DECAP_ARM_TICKS", 3]];
_minCommit  = missionNamespace getVariable ["WFBE_C_AICOM2_DECAP_MIN_COMMIT", 300];
_senseRadius   = missionNamespace getVariable ["WFBE_C_AICOM2_DECAP_SENSE_RADIUS", 3000];
_senseInterval = missionNamespace getVariable ["WFBE_C_AICOM2_DECAP_SENSE_INTERVAL", 4];
_senseChance   = missionNamespace getVariable ["WFBE_C_AICOM2_DECAP_SENSE_CHANCE", 0.35];
_commitRadius  = missionNamespace getVariable ["WFBE_C_AICOM2_DECAP_COMMIT_RADIUS", _senseRadius];

_streak    = _logik getVariable "wfbe_aicom2_decap_streak";
_streak    = if (isNil "_streak") then {0} else {_streak};
_committed = _logik getVariable "wfbe_aicom2_decap_committed";
_committed = if (isNil "_committed") then {false} else {_committed};
_t0        = _logik getVariable "wfbe_aicom2_decap_t0";
_t0        = if (isNil "_t0") then {0} else {_t0};
_senseTick = _logik getVariable "wfbe_aicom2_decap_sensetick";
_senseTick = if (isNil "_senseTick") then {0} else {_senseTick};
_sensed    = _logik getVariable "wfbe_aicom2_decap_sensed";
_sensed    = if (isNil "_sensed") then {false} else {_sensed};

//--- ORGANIC BASE SENSING (owner Q1 2026-07-06): no acting on global HQ knowledge. Count eligible
//--- offensive team leaders within SENSE_RADIUS of the HQ - same team list + same strategy-tick
//--- cadence the stamp loop below already walks (no new scan cost). Then the periodic dice roll:
//--- every SENSE_INTERVAL ticks, chance SENSE_CHANCE, latches _sensed until contact is lost.
//--- No roll, no ARM progress: _sensed=false blocks the streak entirely.
_teams = _logik getVariable ["wfbe_teams", []];
_garTeam = _logik getVariable ["wfbe_aicom_garrison", grpNull];   //--- REAL garrison marker (AssignTowns:246 sets it; the old wfbe_aicom_base_garrison team-var was set NOWHERE - #724 review MAJOR)
_inRange = 0;
if (_enHQAlive) then {
	{
		_t = _x;
		if (!isNull _t && {({alive _x} count (units _t)) > 0}) then {
			//--- REAL eligibility (#724 review MAJOR fix): the old guards checked phantom team-vars set nowhere.
			//--- Garrison = the side-logic wfbe_aicom_garrison group (identity compare, Allocate :406 idiom);
			//--- hold = per-team wfbe_aicom_holding_town latch (cleared to objNull, so isNil alone is not enough -
			//--- AssignTowns :262 idiom); player-led teams excluded like every Allocate eligibility pass (never
			//--- auto-press or sense off a human squad).
			_holdT = _t getVariable "wfbe_aicom_holding_town";
			_isHolding = false;
			if (!isNil "_holdT") then {if (typeName _holdT == "OBJECT" && {!isNull _holdT}) then {_isHolding = true}};
			if (_t != _garTeam && {!_isHolding} && {!isPlayer (leader _t)} && {({alive _x && {(vehicle _x) isKindOf "Air"}} count (units _t)) == 0}) then { //--- stack-pass: GROUND contract - a team with any live unit currently in an Air hull neither senses nor is stamped
				_ldr = leader _t;
				if (!isNull _ldr && {alive _ldr} && {((getPos _ldr) distance _enHQPos) <= _senseRadius}) then {_inRange = _inRange + 1};
			};
		};
	} forEach _teams;
};
_rollNow = 0;
if (_inRange == 0) then {
	_sensed = false;   //--- contact lost -> sensing decays; a fresh roll is required next approach
	_senseTick = 0;
} else {
	if (!_sensed && {!_committed}) then {   //--- stack-pass: no rolls while COMMITTED (kills roll=1 telemetry pollution mid-commit)
		_senseTick = _senseTick + 1;
		if (_senseTick >= _senseInterval) then {
			_senseTick = 0;
			_rollNow = 1;   //--- telemetry: a roll was DUE and evaluated this tick (success = sensed flips 0->1 same tick -> SENSE_CHANCE validatable on soak)
			if ((random 1) < _senseChance) then {_sensed = true};
		};
	};
};

//--- STALL-AWARE ARMING (owner easy-win, 2026-07-08): AI_Commander_Strategy.sqf already tracks
//--- wfbe_aicom_stall_streak (increments while a side sits DOMINANT-BUT-PASSIVE per its own STALL_OVERRIDE
//--- test). Read-only reuse here: once that streak has run STALL_RELAX+ ticks, relax the local DOM_RATIO
//--- 20% so a side sitting just under the normal dominance bar (the documented dominant-but-just-under-
//--- threshold HQ-hunt freeze) can still ARM the Decapitate closer. Additive only - never lowers _domRatio
//--- below what a fresh (streak=0) side already uses, and _dominant's other three legs (sensed/inRange/
//--- enTowns) are unchanged, so a side that never sensed the HQ still never arms.
_stallStreak = _logik getVariable ["wfbe_aicom_stall_streak", 0];
if (_stallStreak >= (missionNamespace getVariable ["WFBE_C_AICOM2_DECAP_STALL_RELAX", 5])) then {_domRatio = _domRatio * 0.8};

_dominant = _enHQAlive
	&& {_sensed}
	&& {_inRange > 0}
	&& {_enTowns <= _maxEnTowns}
	&& {(_enEff <= 0 && {_myEff > 0}) || {_enEff > 0 && {_myEff >= (_enEff * _domRatio)}}};

if (_committed) then {
	if (!_enHQAlive) then {
		_committed = false; _streak = 0; _sensed = false; _senseTick = 0;
		_state = "WON-HQDEAD";
	} else {
		if ((time - _t0) > _minCommit && {_enEff > 0} && {_myEff < (_enEff * _abortRatio)}) then {
			_committed = false; _streak = 0; _sensed = false; _senseTick = 0;
			_state = "ABORT";
			//--- GRUDGE LEDGER (feat/aicom-grudge-ledger, generated by apply_grudge.py): the fist COMMITTED to the enemy HQ and had to abort - stamp a grudge on the nearest town
			if ((missionNamespace getVariable ["WFBE_C_AICOM_GRUDGE", 0]) > 0 && {!isNull _grNearTown}) then {
							private ["_grDecay","_grMax","_grList","_grKeep","_grTrim","_grIdx"];
							_grDecay = missionNamespace getVariable ["WFBE_C_AICOM_GRUDGE_DECAY", 2400];
							_grMax   = missionNamespace getVariable ["WFBE_C_AICOM_GRUDGE_MAX_SITES", 3];
							_grList  = _logik getVariable ["wfbe_aicom_grudge", []];
							_grKeep  = [];
							{ if ((typeName (_x select 0) == "OBJECT") && {!isNull (_x select 0)} && {(_x select 1) > time} && {(_x select 0) != _grNearTown}) then {_grKeep set [count _grKeep, _x]} } forEach _grList;
							if (count _grKeep >= _grMax) then {
								_grTrim = [];
								for "_grIdx" from ((count _grKeep) - _grMax + 1) to ((count _grKeep) - 1) do {_grTrim set [count _grTrim, _grKeep select _grIdx]};
								_grKeep = _grTrim;
							};
							_grKeep set [count _grKeep, [_grNearTown, time + _grDecay, false]];
							_logik setVariable ["wfbe_aicom_grudge", _grKeep];
							diag_log ("AICOM2|v1|GRUDGE_STAMP|" + (str _side) + "|" + str (round (time / 60)) + "|town=" + (_grNearTown getVariable ["name","town"]) + "|source=decap_abort|decay=" + str _grDecay);
			};
		} else {
			_state = "COMMITTED";
		};
	};
} else {
	if (_dominant) then {
		_streak = _streak + 1;
		if (_streak >= _armTicks) then {
			_committed = true; _t0 = time;
			_state = "COMMIT";
		} else {
			_state = "ARMING";
		};
	} else {
		if (_streak > 0) then {_streak = _streak - 1};
		_state = "IDLE";
	};
};

_logik setVariable ["wfbe_aicom2_decap_streak", _streak];
_logik setVariable ["wfbe_aicom2_decap_committed", _committed];
_logik setVariable ["wfbe_aicom2_decap_t0", _t0];
_logik setVariable ["wfbe_aicom2_decap_sensetick", _senseTick];
_logik setVariable ["wfbe_aicom2_decap_sensed", _sensed];

if ((missionNamespace getVariable ["WFBE_C_AICOM2_DECAP_ENABLE", 0]) > 0 && {_committed} && {_enHQAlive}) then {
	_tgtTowns = _snap select WFBE_SNAP_TGTTOWNOBJS;
	_nearTown = objNull; _bestD = 1e12;
	{
		_d = (getPos _x) distance _enHQPos;
		if (_d < _bestD) then {_bestD = _d; _nearTown = _x};
	} forEach _tgtTowns;
	_stamped = 0;
	{
		_t = _x;
		if (!isNull _t && {({alive _x} count (units _t)) > 0}) then {
			//--- REAL eligibility (#724 review MAJOR fix): the old guards checked phantom team-vars set nowhere.
			//--- Garrison = the side-logic wfbe_aicom_garrison group (identity compare, Allocate :406 idiom);
			//--- hold = per-team wfbe_aicom_holding_town latch (cleared to objNull, so isNil alone is not enough -
			//--- AssignTowns :262 idiom); player-led teams excluded like every Allocate eligibility pass (never
			//--- auto-press or sense off a human squad).
			_holdT = _t getVariable "wfbe_aicom_holding_town";
			_isHolding = false;
			if (!isNil "_holdT") then {if (typeName _holdT == "OBJECT" && {!isNull _holdT}) then {_isHolding = true}};
			if (_t != _garTeam && {!_isHolding} && {!isPlayer (leader _t)} && {({alive _x && {(vehicle _x) isKindOf "Air"}} count (units _t)) == 0}) then { //--- stack-pass: GROUND contract - a team with any live unit currently in an Air hull neither senses nor is stamped
				//--- SCOPED COMMIT (owner Q1): only teams already NEAR the HQ press; the rest keep their towns.
				//--- stack-pass MAJOR fixes: stamp must BROADCAST (teams are HC-local; the 2-arg write never
				//--- replicated -> the press layer was dead on the live 2-HC deploy) and clears must use the
				//--- [] SENTINEL (nil cannot network on A2 OA - wfbe_aicom_caplock [] -clear idiom, :1508).
				//--- Plus: mid-drain (caplocked) teams finish their capture before pressing, and the clear
				//--- only fires past 1.2x the commit radius so a boundary team does not flap every tick.
				_ldr = leader _t;
				_capLk = _t getVariable "wfbe_aicom_caplock";
				_capLocked = (!isNil "_capLk") && {typeName _capLk == "ARRAY"} && {count _capLk >= 2};
				_dHQ = if (isNull _ldr) then {1e9} else {(getPos _ldr) distance _enHQPos};
				if (!isNull _ldr && {alive _ldr} && {!_capLocked} && {_dHQ <= _commitRadius}) then {
					_t setVariable ["wfbe_aicom_decap", _enHQPos, true];
					if (!isNull _nearTown) then {_t setVariable ["wfbe_aicom_alloc_target", _nearTown]};
					_stamped = _stamped + 1;
				} else {
					if (_dHQ > (_commitRadius * 1.2) || {isNull _ldr} || {_capLocked}) then {
						//--- out of the press band (or no longer pressable) -> sentinel-clear; TOWN orders untouched.
						_decV = _t getVariable "wfbe_aicom_decap";
						if (!isNil "_decV" && {typeName _decV == "ARRAY"} && {count _decV >= 2}) then {_t setVariable ["wfbe_aicom_decap", [], true]};
					};
				};
			} else {
				//--- became garrison/hold while committed -> the press stamp no longer applies; clear it (latent-consumer guard).
				_decV = _t getVariable "wfbe_aicom_decap"; if (!isNil "_decV" && {typeName _decV == "ARRAY"} && {count _decV >= 2}) then {_t setVariable ["wfbe_aicom_decap", [], true]}; //--- sentinel+broadcast (stack-pass)
			};
		} else {
			if (!isNull _t) then {_decV = _t getVariable "wfbe_aicom_decap"; if (!isNil "_decV" && {typeName _decV == "ARRAY"} && {count _decV >= 2}) then {_t setVariable ["wfbe_aicom_decap", [], true]}}; //--- sentinel+broadcast (stack-pass)
		};
	} forEach _teams;
} else {
	{ if (!isNull _x) then {_decV = _x getVariable "wfbe_aicom_decap"; if (!isNil "_decV" && {typeName _decV == "ARRAY"} && {count _decV >= 2}) then {_x setVariable ["wfbe_aicom_decap", [], true]}} } forEach _teams; //--- sentinel+broadcast (stack-pass)
	_stamped = 0;
};

_sideText = str _side;
_elMin = round (time / 60);
diag_log ("AICOM2|v1|DECAP|" + _sideText + "|" + str _elMin
	+ "|state=" + _state
	+ "|streak=" + str _streak
	+ "|committed=" + (if (_committed) then {"1"} else {"0"})
	+ "|myEff=" + str _myEff + "|enEff=" + str _enEff
	+ "|enTowns=" + str _enTowns + "|myTowns=" + str _myTowns
	+ "|enHQ=" + (if (_enHQAlive) then {"alive"} else {"dead"})
	+ "|inRange=" + str _inRange
	+ "|roll=" + str _rollNow
	+ "|sensed=" + (if (_sensed) then {"1"} else {"0"})
	+ "|stamped=" + str _stamped
	+ "|flag=" + str (missionNamespace getVariable ["WFBE_C_AICOM2_DECAP_ENABLE", 0]));
