//--- Author [ICE] & Net_2

player createDiaryRecord["Diary", ["Gameplay Summary", "<br/>Warfare is a blend of a team-based multiplayer mission and realtime strategy, where BLUFOR and OPFOR fight for the control of the map. Both sides are lead by a commander, who influences his side's strategy.<br/><br/>There are two kinds of resources: <t color='#F5D363'>Supply</t> is used by the commander for building and upgrading factories. <t color='#F5D363'>Cash</t> is used to purchase weapons, units and vehicles."]];

player createDiaryRecord["Diary", ["Your Task", "<br/>Your tasks are:<br/><br/>1. Capture towns from local resistance and the enemy team.<br/><br/>2. Destroy the enemy base and HQ.<br/><br/>3. Defend your own base and HQ."]];

player createDiaryRecord["Diary", ["Getting Started", "<br/>Most actions happen via the <t color='#F5D363'>WF menu</t> — open it with your mouse scroll wheel.<br/><br/>You need to be inside a base perimeter or near a factory to use it. If needed, respawn and choose a base spawn point on the map.<br/><br/>Barracks [B] — gear and infantry. Light Factory [LF] — light vehicles. Heavy Factory [HF] — tanks and APCs. Air Factory [AF] — helicopters and aircraft. Service Point [SP] — rearm, repair, refuel.<br/><br/>Special vehicles are colour-coded in the Buy Units menu; single-click any entry for a usage hint.<br/><br/>Build a Command Center [CC] to enable remote purchasing from anywhere on the map, to fire artillery missions, and to start upgrades. Build an Anti-Air Radar [AAR] to track enemy aircraft and to unlock the Counter Battery Radar."]];

player createDiaryRecord["Diary", ["Commander", "<br/>The commander should be a player. The commander can:<br/><br/>- Deploy and relocate the HQ (Mobile HQ vehicle)<br/>- Build and sell factories and defenses from the Construction Menu (near HQ)<br/>- Research upgrades via WF menu → Factory Upgrade<br/>- Buy WDDM commander compositions (up to 3 per base area)<br/>- Issue capture orders and objectives to the team<br/><br/>Build factories early, keep supply for the CBR and Bank. Focus upgrade supply on barracks and the factory type your team needs most."]];

player createDiaryRecord["Diary", ["Capturing Towns", "<br/>Capture a town by taking its strongpoints (small bunkers around the town circle) first, then dominating the main town depot (50 m radius).<br/><br/>Captured strongpoints are respawn points as long as you are inside the town range.<br/><br/><t color='#F5D363'>Capture grace period</t>: after your side takes a town, defenders get 5 minutes before enemy AI can respawn there, and lingering defenders have 3 minutes to clear out. Use this window to consolidate."]];

player createDiaryRecord["Diary", ["Building Bases (As Commander)", "<br/>Each side starts with one Mobile HQ [MHQ]. Deploy it to build a base. After the HQ is placed, you can add Barracks, Light/Heavy/Air factories, a Command Center, Anti-Air Radar, and a Service Point from the Construction Menu.<br/><br/>The HQ can be packed up and redeployed. You can have multiple bases. Defense budget is capped per category per base (scales with barracks level) — statics and mines are blocked if 3+ enemy ground units are inside base range."]];

player createDiaryRecord["Diary", ["Experital Changes", "<br/><t size='1.2' color='#F5D363'>Economy</t><br/>Both sides start with <t color='#F5D363'>$11,600 cash and 7,400 supply</t>.<br/><br/><t size='1.2' color='#F5D363'>Bank (endgame)</t><br/>Build the <t color='#F5D363'>Federal Reserve / Bank Rossii</t> (9,500 supply; must be placed more than 800 m from your HQ). While your HQ stands it pays $5,000 total every 5 minutes, split among living team members. Destroying the enemy bank awards +$40,000 side supply and $7,500 to the killer. Both banks are marked on the map for both sides.<br/><br/><t size='1.2' color='#F5D363'>Counter Battery Radar (CBR)</t><br/>Build the CBR (2,400 supply) to detect and mark enemy artillery firing positions for 75 seconds. Requires your AAR to be alive. The CBR Radar upgrade extends its detection radius: 750 m → 1,500 m → 2,000 m. Capturing an airfield gives your side a permanent 2,000 m CBR for that airfield.<br/><br/><t size='1.2' color='#F5D363'>Airfields</t><br/>NWAF, NEAF and Balota Airfield are capturable towns (50 SV garrison). Holding an airfield provides a repair point and an exclusive hangar stocking unique aircraft unavailable elsewhere (L-39, An-2, Mi-17 variants on Chernarus).<br/><br/><t size='1.2' color='#F5D363'>Capture-to-Unlock Premium Units</t><br/>Holding <t color='#F5D363'>Krasnostav</t> unlocks the Czech T-72 (Heavy Factory level 4, $7,000). Holding <t color='#F5D363'>NW Airfield</t> unlocks the RM-70 rocket artillery (Light Factory level 4, $6,800, fully integrated into artillery fire missions). Both unlock for the holding side only.<br/><br/><t size='1.2' color='#F5D363'>Patrols and Convoys</t><br/>Research the Patrols upgrade (4 levels — supply cost 300 / 1,600 / 2,400 / 3,200). Patrols spawn near your HQ and push toward the frontline capturing towns as they go (max 3 active per side). Level 4 Convoys add a supply truck to each patrol that pays your whole team $750 split equally at every town stop. Active patrols reduce each player's max AI by 1.<br/><br/><t size='1.2' color='#F5D363'>Factory Queue and Buy Menu</t><br/>The buy menu shows the current queue depth as <t color='#F5D363'>N/CAP</t>. Queue caps scale with factory level: Barracks min 10, Light Factory min 5, Heavy/Aircraft min 3. You can cancel the last queued order for a refund (capped at 50% for orders that had a discount applied).<br/><br/><t size='1.2' color='#F5D363'>Medic Redeployment Truck</t><br/>Medics only: a forward spawn truck purchasable from the Light Factory (violet row). It activates when parked with engine off, a free cargo seat, and at least 500 m from any non-friendly town.<br/><br/><t size='1.2' color='#F5D363'>Classes</t><br/>Your class and its abilities are shown as a hint when you spawn and again from the Class Info action in your action menu. Class tags (SOL/SUP/MED/ENG/SNI) appear on the map."]];

player createDiaryRecord["Diary", ["Mods", "<br/>We strongly suggest downloading and enabling the mods listed on our Discord. They improve the experience enormously!"]];

player createDiaryRecord["Diary", ["Our Discord", "<br/>DISCORD (open link with a browser): >>> discord.me/warfare <<<.<br/><br/>Backup link: >>> discord.gg/knXvYMX <<<.<br/><br/>Help cover server costs by becoming a Patron at >> patreon.com/WarfareArma2 << or send a message to Miksuu on Discord.<br/><br/>An FPS optimisation guide is available in the Discord — worth checking if you experience performance issues."]];













