#define WF_DEBUG 1
#define WF_LOG_CONTENT
//#define IS_CHERNARUS_MAP_DEPENDENT
//#define IS_MOD_MAP_DEPENDENT
//#define IS_NAVAL_MAP
//#define IS_AIR_WAR_EVENT
#define IS_ZARGABAD_LOWPOP_MAP
#define WF_MAXPLAYERS 31
#define WF_MISSIONNAME "[31] Warfare V48 Zargabad"
#define STARTING_DISTANCE 2500
#define COMBINEDOPS 1
#define WF_RESPAWNDELAY 2