param(
	[string]$OutputPath = ".\zargabad-evidence",
	[switch]$Force
)

$ErrorActionPreference = "Stop"

$resolvedOutput = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($OutputPath)
if ((Test-Path -LiteralPath $resolvedOutput) -and -not (Test-Path -LiteralPath $resolvedOutput -PathType Container)) {
	throw "Evidence output path exists but is not a directory: $resolvedOutput"
}
if ((Test-Path -LiteralPath $resolvedOutput) -and -not $Force) {
	$existing = @(Get-ChildItem -LiteralPath $resolvedOutput -Force)
	if ($existing.Count -gt 0) {
		throw "Evidence output directory is not empty: $resolvedOutput. Use -Force to reuse it."
	}
}
if (-not (Test-Path -LiteralPath $resolvedOutput)) {
	New-Item -ItemType Directory -Path $resolvedOutput | Out-Null
}

$mapAuditPath = Join-Path $resolvedOutput "zargabad-map-audit.md"
$mapAuditTool = Join-Path $PSScriptRoot "New-ZargabadMapAuditPacket.ps1"
& $mapAuditTool -OutputPath $mapAuditPath | Out-Host

$readmePath = Join-Path $resolvedOutput "README-zargabad-evidence.md"
$readme = @(
	'# Zargabad Runtime Evidence Folder',
	"",
	'Put Claude/runtime tester evidence for the current pass in this directory.',
	"",
	'## Required Files',
	"",
	'- `zargabad-map-audit.md` generated by `Tools/New-ZargabadMapAuditPacket.ps1`.',
	'- Real PNG/JPEG screenshots referenced by `zargabad-runtime-report.md`.',
	'- `zargabad-runtime-report.md` can live beside this folder or inside it, but validate it with `-EvidenceRoot` pointing here.',
	"",
	'## Suggested Screenshot Names',
	"",
	'- `population-city-airfield.png`',
	'- `population-farms-outskirts.png`',
	'- `base-west-sightline.png`',
	'- `base-east-sightline.png`',
	'- `base-static-arcs.png`',
	'- `wall-origin-axis.png`',
	'- `wall-gaps-pathing.png`',
	'- `town-defense-blocking.png`',
	'- `priority-defense-arcs.png`',
	'- `rim-illegal-removal.png`',
	'- `rim-legal-allow.png`',
	"",
	'## Validate',
	"",
	'```powershell',
	('powershell -NoProfile -ExecutionPolicy Bypass -File Tools\Validate-ZargabadRuntimeReport.ps1 -ReportPath ".\zargabad-runtime-report.md" -EvidenceRoot "{0}" -RequireJip -RequireHeadlessClient -RequireEdgeGuardRemoval -RequireEdgeGuardSafeAllow -RequireNamedRimPoints -RequireBlackMarket' -f $resolvedOutput),
	'```',
	"",
	'Every screenshot filename used in `Claude Notes` or `Objective Coverage` must exist here and have a PNG/JPEG signature. The validator also checks that `zargabad-map-audit.md` contains Population Flow, Rim Test Points, WDDM Fortification Review, and Claude Screenshot Targets sections.'
)
Set-Content -LiteralPath $readmePath -Value ($readme -join "`r`n") -Encoding UTF8

Write-Host "Prepared Zargabad evidence folder: $resolvedOutput"
Write-Host "Map audit packet: $mapAuditPath"
Write-Host "Evidence README: $readmePath"
